# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Challenge_Odontoprev_API/Challenge_Odontoprev_API.csproj'  # Verifique se este caminho est치 correto
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webAppName: 'apidotnet-grcnceb9e4gmbudn'  # Nome exato do Web App no Azure
  githubRepo: 'https://github.com/Arayopedro/Challenge_Odontoprev_API-main'

steps:
# Tarefa para diagn칩stico - ajuda a ver a estrutura de arquivos
- script: |
    echo "Estrutura de diret칩rios:"
    dir /s /b
    echo "Arquivos .csproj encontrados:"
    dir /s /b *.csproj
    echo "Arquivos .sln encontrados:"
    dir /s /b *.sln
  displayName: 'Listar estrutura de arquivos'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
# Publicar os artefatos de build para uso posterior
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Adicione a tarefa de deploy ap칩s o build e teste
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(acf1a434-8f45-4851-b284-f12fa385388f)'
    appType: 'webApp'
    WebAppName: '$(webAppName)'
    packageForLinux: '$(build.artifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
    AppSettings: '-WEBSITE_TIME_ZONE "E. South America Standard Time"'